version: '3.7'
networks:
  setnet:
   driver: bridge
   name: setnet
   external: true

services:
  server:
    build:
      context: .
    environment:
      - DB_URI=${DB_URI}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - 3000:3000
    depends_on:
      - mongo1
    command: npm run start-dev
    networks:
      - setnet
  mongo1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      - setnet

volumes:
  mongo1_data:
  mongo1_config:
    


